events {}

http {
  server {
    listen 2375;

    location / {
      proxy_pass http://unix:/var/run/docker.sock:;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header Connection "";
      proxy_buffering off;
    }
  }
}
